[install]
# Configurações de instalação
cache = true
production = false

[test]
# Configurações para testes
timeout = 30000
preload = ["./tests/setup/test-setup.ts"]
coverage = true
coverageDir = "./coverage"

[run]
# Configurações de execução
hot = true
watch = true

[install]
# Configurações de path mapping
preinstall = []
