global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 2s
    metrics_path: /metrics

  # Métricas do OpenTelemetry Collector via Prometheus exporter
  - job_name: 'otel-collector-prometheus'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 2s
    metrics_path: /metrics

  # Payment API - endpoint de métricas
  - job_name: 'payment-api'
    static_configs:
      - targets: ['payment-api:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

# Configurações de alerting (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Configurações de regras de alerta (opcional)
# rule_files:
#   - "alert_rules.yml"
